run-name: ${{github.actor}} is deploying to AWS EC2 server
on: [push]
jobs: 
  building-and-running-the-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: install dependencies
        run: |
          cd jobio-front &&
          sudo npm install &&
          cd .. &&
          cd jobio-back &&
          sudo npm install &&
          cd ..
      - name: installing and running docker
        run: |
          sudo npm install docker &&
          sudo service docker start
      - name: Build the Docker images
        run: |
          docker build -t mishafomenko/jobio:frontend-1.0 ./jobio-front
          docker build --build-arg SERVICE_ACCOUNT_A="${{ secrets.SERVICE_ACCOUNT }}" -t mishafomenko/jobio:backend-1.0 ./jobio-back
      - name: Log in to Docker Hub
        run: docker login -u mishafomenko -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Push Docker images to Docker Hub
        run: |
          docker push mishafomenko/jobio:frontend-1.0
          docker push mishafomenko/jobio:backend-1.0
      - name: creating the .pem key file
        run: |
          sudo echo "${{secrets.JOBIO_PEM}}" > jobio.pem
          sudo chmod 400 jobio.pem
      - name: stopping the previous containers
        run: |
          ssh -i "jobio.pem" -o StrictHostKeyChecking=no ec2-user@ec2-18-218-30-148.us-east-2.compute.amazonaws.com sudo service docker stop
      - name: restarting docker daemon
        run: |
          ssh -i "jobio.pem" -o StrictHostKeyChecking=no ec2-user@ec2-18-218-30-148.us-east-2.compute.amazonaws.com sudo service docker start
      - name: deleting the previous containers
        run: |
          ssh -i "jobio.pem" -o StrictHostKeyChecking=no ec2-user@ec2-18-218-30-148.us-east-2.compute.amazonaws.com sudo docker system prune -af
      - name: pulling the new images from dockerhub
        run: |
          ssh -i "jobio.pem" -o StrictHostKeyChecking=no ec2-user@ec2-18-218-30-148.us-east-2.compute.amazonaws.com sudo docker pull mishafomenko/jobio:backend-1.0 
          ssh -i "jobio.pem" -o StrictHostKeyChecking=no ec2-user@ec2-18-218-30-148.us-east-2.compute.amazonaws.com sudo docker pull mishafomenko/jobio:frontend-1.0 
      - name: running the new images
        run: |
          ssh -i "jobio.pem" -o StrictHostKeyChecking=no ec2-user@ec2-18-218-30-148.us-east-2.compute.amazonaws.com sudo docker run -d -p 3001:3001 mishafomenko/jobio:backend-1.0 
          ssh -i "jobio.pem" -o StrictHostKeyChecking=no ec2-user@ec2-18-218-30-148.us-east-2.compute.amazonaws.com sudo docker run -d -p 80:3000 mishafomenko/jobio:frontend-1.0 